### ISSUE TITLE
中文用这个加密会出现微信服务器无法解密的问题

### ISSUE THREAD

**Issue by fkxxyz** [vhash/WXBizMsgCrypt#1]
用了你这个脚本，踩了个巨大的坑，调试了好几个小时。
WXBizMsgCrypt.py 的 [第 156 行](https://github.com/vhash/WXBizMsgCrypt/blob/master/WXBizMsgCrypt.py#L156)

需要改成

```python
text = self.get_random_str().encode('utf-8') + struct.pack("I",socket.htonl(len(text.encode('utf-8')))) + text.encode('utf-8') + appid.encode('utf-8')
```

否则会出现，只要有中文，就会无法解密的情况。
有中文时，len(text) 和 len(text.encode('utf-8') 的值是不一样的，后者要大，会导致微信服务器端解密的过程中长度偏小导致解密失败。

**Comment by vhash** [comment]
好的，谢谢，已经修复了
